let defaults = {
  showLastVisited: true,
  useISODate: false,
  lastVisitedInFront: false,
  bookmarkedPrefix: "🔖",
  visitedPrefix: "🕒",
  lastVisitedOlderThan: 0,
  lastVisitedQueryLimit: 5,
  lastVisitedTwoDates: false,
  useCustomFormat: false,
  customOverLink: "%u %+[%B%+]%-[%+(%V%+)%-]%+((%T%+{; %t%+})%+)",
  customDateDefault: "%a, %Y-%m-%d %H:%M",
  customWeekdayNames: chrome.i18n.getMessage("customWeekdayNames.default"),
  customMonthNames: chrome.i18n.getMessage("customMonthNames.default"),
  customLimit0: 60,
  customDate0: chrome.i18n.getMessage("customDate0.default"),
  customLimit1: 3600,
  customDate1: chrome.i18n.getMessage("customDate1.default"),
  customLimit2: 86400,
  customDate2: chrome.i18n.getMessage("customDate2.default"),
  customLimit3: 648000,
  customDate3: chrome.i18n.getMessage("customDate3.default"),
  customLimit4: 0,
  customDate4: chrome.i18n.getMessage("customDate4.default"),
  customLimit5: 0,
  customDate5: chrome.i18n.getMessage("customDate5.default"),
  customLimit6: 0,
  customDate6: chrome.i18n.getMessage("customDate6.default")
};
