let defaults = {
  showLastVisited: true,
  useISODate: false,
  lastVisitedInFront: false,
  bookmarkedPrefix: "🔖",
  visitedPrefix: "🕒",
  lastVisitedOlderThan: 0,
  lastVisitedQueryLimit: 5,
  lastVisitedTwoDates: false,
  useCustomFormat: false,
  customOverLink: "%u %+[%B%+]%-[%+(%V%+)%-]%+((%T%+{; %t%+})%+)",
  customDateDefault: "%a, %Y-%m-%d %H:%M",
  customWeekdayNames: chrome.i18n.getMessage("customWeekdayNames_default"),
  customMonthNames: chrome.i18n.getMessage("customMonthNames_default"),
  customLimit0: 60,
  customDate0: chrome.i18n.getMessage("customDate0_default"),
  customLimit1: 3600,
  customDate1: chrome.i18n.getMessage("customDate1_default"),
  customLimit2: 86400,
  customDate2: chrome.i18n.getMessage("customDate2_default"),
  customLimit3: 648000,
  customDate3: chrome.i18n.getMessage("customDate3_default"),
  customLimit4: 0,
  customDate4: chrome.i18n.getMessage("customDate4_default"),
  customLimit5: 0,
  customDate5: chrome.i18n.getMessage("customDate5_default"),
  customLimit6: 0,
  customDate6: chrome.i18n.getMessage("customDate6_default")
};
